services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "7545:7545"
    networks:
      - acecoin-network

  smart-contracts:
    build:
      context: ./smart-contracts
      dockerfile: Dockerfile
    volumes:
      - ./smart-contracts:/app
      - /app/node_modules
      - smart-contracts-build:/app/build/contracts
    command: npm run build
    depends_on:
      - ganache
    networks:
      - acecoin-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ../smart-contracts/build/contracts:/contracts
    ports:
      - "3000:3000"
    depends_on:
      - smart-contracts
      - ganache
    networks:
      - acecoin-network


volumes:
  smart-contracts-build:

networks:
  acecoin-network: