version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli -h 0.0.0.0 --networkId 5777
    ports:
      - '8545:8545'
    networks:
      - acecoin-network

  smart-contracts:
    build:
      context: ./smart-contracts
    command: truffle migrate --reset --network development
    volumes:
      - ./smart-contracts:/app
      - /app/node_modules
      - smart-contracts-build:/app/build/contracts
      - ./smart-contracts/contracts:/app/contracts
    depends_on:
      - ganache
    networks:
      - acecoin-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_CONTRACT_ADDRESS=your_contract_address
      - NEXT_PUBLIC_NETWORK_ID=5777
    volumes:
      - ./frontend:/app
      - smart-contracts-build:/app/contracts
    depends_on:
      - smart-contracts
    networks:
      - acecoin-network

volumes:
  smart-contracts-build:

networks:
  acecoin-network: