version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache
    platform: linux/arm64/v8
    ports:
      - "8545:8545"
    command: --accounts 10 --defaultBalanceEther 100
    networks:
      - acecoin-network

  coin-svc:
    build:
      context: ./coin-svc
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - ganache
    environment:
      ETH_NODE_URL: ${ETH_NODE_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - acecoin-network

  signing-svc:
    build:
      context: ./signing-svc
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - ganache
    environment:
      ETH_NODE_URL: ${ETH_NODE_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - acecoin-network

  document-svc:
    build:
      context: ./document-svc
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
    depends_on:
      - ganache
    environment:
      ETH_NODE_URL: ${ETH_NODE_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - acecoin-network

  user-svc:
    build:
      context: ./user-svc
      dockerfile: Dockerfile
    ports:
      - "8084:3000"
    depends_on:
      - ganache
    environment:
      ETH_NODE_URL: ${ETH_NODE_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - acecoin-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - document-svc
      - user-svc
    networks:
      - acecoin-network

  smart-contracts:
    build:
      context: ./smart-contracts
      dockerfile: Dockerfile
    depends_on:
      - ganache
    networks:
      - acecoin-network

networks:
  acecoin-network:
    driver: bridge
